### ISSUE TITLE
Değişken kelimesi

### ISSUE THREAD

**Issue by c0b41** [ustun/turkcescript#1]
Bence değişken kelimesi yeterince uzun bir kelime ben var kelimesi yerine bunu tercih etmem tam tersine değer kelimesi olması gerektiğini düşünüyorum.

**Comment by ustun** [comment]
Değer, daha çok value'ya tekabül ediyor. Değişmeyen değerler için kullanılması daha uygun diye düşünüyorum.

**Comment by c0b41** [comment]
Söylediğin daha çok const'a hitap ediyor var ile tanımlanan değerler değiştirilebiliyor tabi birde let var

**Comment by ustun** [comment]
Evet, const için ya değer ya da sabit ekleyeceğim.

**Comment by ustun** [comment]
Let için velev ki olabilir. :) şaka bir yana let'e ne demek gerek acaba?

**Comment by c0b41** [comment]
Bence ayrı bir issue açıp öneriler almak gerek :) let en karmaşık olanı katılıyorum
